import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });
const clashDisplay = localFont({
  src: [
    {
      path: "./../../public/fonts/ClashDisplay-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/fonts/ClashDisplay-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-clash-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${clashDisplay.variable} text-white bg-black pt-10`}
      >
        {children}
      </body>
    </html>
  );
}
