import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import localFont from 'next/font/local'

const poppins = Poppins({ weight: ['400', '600'], subsets: ['latin'] })
const clashDisplay = localFont({
  src: [
    {
      path: './../../public/fonts/ClashDisplay-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './../../public/fonts/ClashDisplay-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-clash-display'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${clashDisplay.variable} text-white bg-black py-10`}>
        <div className='max-w-[1728px] mx-auto grid grid-cols-12'>
          <div className='col-span-10 col-start-2'>{children}</div>
        </div>
      </body>
    </html>
  )
}
